Support GCC’s ThreadSanitizer.
cameron314/readerwriterqueue pull request #157
Opened 2024-07-01 09:23 UTC by PromyLOPh

GCC may or may not support __has_feature, depending on its version, but it does expose a different macro to check for the presence of the ThreadSanitizer during compile-time.

2024-07-08 04:06 UTC, cameron314 requested changes

2024-07-08 04:06 UTC, cameron314 commented on atomicops.h
> +#define _TSAN_IS_ENABLED 1
This is a reserved name and cannot be used

2024-07-08 04:06 UTC, cameron314 commented on atomicops.h
> +#if _TSAN_IS_ENABLED
How does this compile? This introduces a new `#if` but _removes_ an `#endif` instead of adding a corresponding one.

2024-07-08 04:09 UTC, cameron314 commented on atomicops.h
> +#define _TSAN_IS_ENABLED 1
```suggestion
#define AE_TSAN_IS_ENABLED 1
```

2024-07-08 06:07 UTC, PromyLOPh commented
If there’s a chance both feature test macros are supported (not sure), we might want to change the code to
```diff
diff --git a/atomicops.h b/atomicops.h
index a641333..1ebde3d 100644
--- a/atomicops.h
+++ b/atomicops.h
@@ -47,9 +47,8 @@
 // For GCC
 #if defined(__SANITIZE_THREAD__)
 #define AE_TSAN_IS_ENABLED 1
-#endif
 // For clang
-#if defined(__has_feature)
+#elif defined(__has_feature)
 #if __has_feature(thread_sanitizer)
 #define AE_TSAN_IS_ENABLED 1
 #endif
```
to avoid warnings about re-defined preprocessor macros.

2024-07-08 17:50 UTC, cameron314 commented on atomicops.h
> +#if AE_TSAN_IS_ENABLED
```suggestion
#ifdef AE_TSAN_IS_ENABLED
```

2024-07-08 17:50 UTC, cameron314 commented on atomicops.h
> +#define AE_TSAN_IS_ENABLED 1
```suggestion
#define AE_TSAN_IS_ENABLED
```

2024-07-08 17:50 UTC, cameron314 commented on atomicops.h
> +#define AE_TSAN_IS_ENABLED 1
```suggestion
#define AE_TSAN_IS_ENABLED
```

2024-07-08 17:50 UTC, cameron314 commented on atomicops.h
>  #if __has_feature(thread_sanitizer)
```suggestion
#if __has_feature(thread_sanitizer) && !defined(AE_TSAN_IS_ENABLED)
```

2024-07-09 11:20 UTC, cameron314 approved these changes

2024-07-09 11:20 UTC, merged

2024-07-09 11:20 UTC, cameron314 commented
Thanks!